/cm/local/apps/slurm/var/spool/job417802/slurm_script: line 19: /common/ketrong/minconda3/etc/profile.d/conda.sh: No such file or directory
/cm/local/apps/slurm/var/spool/job417802/slurm_script: line 22: $'\nconda create --name tpot2devenv -c conda-forge python=3.10\n': command not found
/cm/local/apps/slurm/var/spool/job417802/slurm_script: line 27: $'\npip install -r requirements.txt\n': command not found
RunStart
2023-11-28 15:52:46.043226: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-28 15:52:46.077709: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-28 15:52:46.077734: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-28 15:52:46.078851: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-28 15:52:46.084319: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-28 15:52:48.102542: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:tensorflow:From /home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:108: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
start
working on 
tpot2_imputetest/Impute_Experiments/logs//small_run
loading data
tpot2_imputetest/Impute_Experiments/data/26_True.pkl
starting impute modules
running experiment 1/3 - Does large hyperparameter space improve reconstruction accuracy over simple
[I 2023-11-28 15:53:02,787] A new study created in memory with name: no-name-7a9bb88b-2378-4721-a95c-39769f7d97a4
[W 2023-11-28 15:53:02,789] Trial 0 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:02,792] Trial 0 failed with value None.
[W 2023-11-28 15:53:02,789] Trial 1 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:02,793] Trial 1 failed with value None.
[W 2023-11-28 15:53:02,793] Trial 3 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:03,003] Trial 3 failed with value None.
[W 2023-11-28 15:53:02,790] Trial 2 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:03,149] Trial 2 failed with value None.
[W 2023-11-28 15:53:03,001] Trial 6 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:03,292] Trial 6 failed with value None.
[W 2023-11-28 15:53:03,002] Trial 7 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:03,434] Trial 7 failed with value None.
[W 2023-11-28 15:53:03,000] Trial 4 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:03,578] Trial 4 failed with value None.
[W 2023-11-28 15:53:03,149] Trial 9 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:03,722] Trial 9 failed with value None.
[W 2023-11-28 15:53:03,292] Trial 12 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:03,869] Trial 12 failed with value None.
[W 2023-11-28 15:53:03,002] Trial 8 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:04,009] Trial 8 failed with value None.
[W 2023-11-28 15:53:03,291] Trial 10 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:04,152] Trial 10 failed with value None.
[W 2023-11-28 15:53:03,291] Trial 11 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:04,293] Trial 11 failed with value None.
[W 2023-11-28 15:53:03,868] Trial 15 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:04,438] Trial 15 failed with value None.
[W 2023-11-28 15:53:03,722] Trial 13 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:04,585] Trial 13 failed with value None.
[W 2023-11-28 15:53:04,152] Trial 17 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:04,725] Trial 17 failed with value None.
[W 2023-11-28 15:53:03,001] Trial 5 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:04,867] Trial 5 failed with value None.
[W 2023-11-28 15:53:04,582] Trial 18 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:05,012] Trial 18 failed with value None.
[W 2023-11-28 15:53:04,009] Trial 16 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:05,155] Trial 16 failed with value None.
[W 2023-11-28 15:53:04,585] Trial 19 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:05,297] Trial 19 failed with value None.
[W 2023-11-28 15:53:05,010] Trial 21 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:05,438] Trial 21 failed with value None.
[W 2023-11-28 15:53:05,154] Trial 23 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:05,580] Trial 23 failed with value None.
[W 2023-11-28 15:53:05,155] Trial 24 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:05,720] Trial 24 failed with value None.
[W 2023-11-28 15:53:05,011] Trial 22 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:05,863] Trial 22 failed with value None.
[W 2023-11-28 15:53:04,866] Trial 20 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:06,007] Trial 20 failed with value None.
[W 2023-11-28 15:53:06,005] Trial 25 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:06,154] Trial 25 failed with value None.
[W 2023-11-28 15:53:06,007] Trial 26 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:06,296] Trial 26 failed with value None.
[W 2023-11-28 15:53:06,152] Trial 27 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:06,440] Trial 27 failed with value None.
[W 2023-11-28 15:53:06,296] Trial 28 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:06,582] Trial 28 failed with value None.
[W 2023-11-28 15:53:03,867] Trial 14 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:06,725] Trial 14 failed with value None.
[W 2023-11-28 15:53:06,865] Trial 29 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:06,866] Trial 29 failed with value None.
[W 2023-11-28 15:53:07,008] Trial 30 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:07,008] Trial 30 failed with value None.
[W 2023-11-28 15:53:07,149] Trial 31 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:07,150] Trial 31 failed with value None.
[W 2023-11-28 15:53:07,292] Trial 32 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:07,293] Trial 32 failed with value None.
[W 2023-11-28 15:53:07,435] Trial 33 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:07,436] Trial 33 failed with value None.
[W 2023-11-28 15:53:07,576] Trial 34 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:07,576] Trial 34 failed with value None.
[W 2023-11-28 15:53:07,718] Trial 35 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:07,718] Trial 35 failed with value None.
[W 2023-11-28 15:53:07,860] Trial 36 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:07,860] Trial 36 failed with value None.
[W 2023-11-28 15:53:08,001] Trial 37 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:08,001] Trial 37 failed with value None.
[W 2023-11-28 15:53:08,144] Trial 38 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:08,144] Trial 38 failed with value None.
[W 2023-11-28 15:53:08,286] Trial 39 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:08,287] Trial 39 failed with value None.
[W 2023-11-28 15:53:08,427] Trial 40 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:08,428] Trial 40 failed with value None.
[W 2023-11-28 15:53:08,568] Trial 41 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:08,568] Trial 41 failed with value None.
[W 2023-11-28 15:53:08,709] Trial 42 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:08,710] Trial 42 failed with value None.
[W 2023-11-28 15:53:08,851] Trial 43 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:08,851] Trial 43 failed with value None.
[W 2023-11-28 15:53:08,993] Trial 44 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:08,994] Trial 44 failed with value None.
[W 2023-11-28 15:53:08,994] Trial 45 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:09,135] Trial 45 failed with value None.
[W 2023-11-28 15:53:09,134] Trial 46 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:09,276] Trial 46 failed with value None.
[W 2023-11-28 15:53:09,416] Trial 47 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:09,416] Trial 47 failed with value None.
Traceback (most recent call last):
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/small_main.py", line 107, in <module>
    main()
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/small_main.py", line 69, in main
    automodel.fit(X=X_train_missing)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 61, in fit
    self.study.optimize(obj, n_trials=self.n_trials, n_jobs=self.n_jobs, show_progress_bar=self.show_progress, gc_after_trial=self.garbage_collect)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/study.py", line 451, in optimize
    _optimize(
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 103, in _optimize
    f.result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    raise func_err
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
srun: error: esplhpc-cp005: task 0: Exited with exit code 1
