/cm/local/apps/slurm/var/spool/job417798/slurm_script: line 19: /common/ketrong/minconda3/etc/profile.d/conda.sh: No such file or directory
/cm/local/apps/slurm/var/spool/job417798/slurm_script: line 22: $'\nconda create --name tpot2devenv -c conda-forge python=3.10\n': command not found
/cm/local/apps/slurm/var/spool/job417798/slurm_script: line 27: $'\npip install -r requirements.txt\n': command not found
RunStart
2023-11-28 15:53:11.208181: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-28 15:53:11.244045: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-28 15:53:11.244070: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-28 15:53:11.245452: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-28 15:53:11.251605: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-28 15:53:12.383619: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:tensorflow:From /home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:108: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
start
working on 
tpot2_imputetest/Impute_Experiments/logs//small_run
loading data
tpot2_imputetest/Impute_Experiments/data/26_True.pkl
starting impute modules
running experiment 1/3 - Does large hyperparameter space improve reconstruction accuracy over simple
[I 2023-11-28 15:53:28,954] A new study created in memory with name: no-name-7652180b-c932-469b-94b9-cf63f5209c4d
[W 2023-11-28 15:53:28,956] Trial 0 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:28,958] Trial 0 failed with value None.
[W 2023-11-28 15:53:28,957] Trial 1 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:29,218] Trial 1 failed with value None.
[W 2023-11-28 15:53:28,958] Trial 2 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:29,403] Trial 2 failed with value None.
[W 2023-11-28 15:53:29,588] Trial 3 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:29,589] Trial 3 failed with value None.
[W 2023-11-28 15:53:29,774] Trial 4 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:29,775] Trial 4 failed with value None.
[W 2023-11-28 15:53:29,775] Trial 5 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:29,963] Trial 5 failed with value None.
[W 2023-11-28 15:53:29,960] Trial 6 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:30,145] Trial 6 failed with value None.
[W 2023-11-28 15:53:29,961] Trial 8 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:30,327] Trial 8 failed with value None.
[W 2023-11-28 15:53:29,963] Trial 10 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:30,511] Trial 10 failed with value None.
[W 2023-11-28 15:53:30,144] Trial 11 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:30,691] Trial 11 failed with value None.
[W 2023-11-28 15:53:29,962] Trial 9 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:30,875] Trial 9 failed with value None.
[W 2023-11-28 15:53:29,961] Trial 7 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:31,057] Trial 7 failed with value None.
[W 2023-11-28 15:53:31,243] Trial 12 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:31,243] Trial 12 failed with value None.
[W 2023-11-28 15:53:31,427] Trial 13 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:31,428] Trial 13 failed with value None.
[W 2023-11-28 15:53:31,428] Trial 14 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:31,612] Trial 14 failed with value None.
[W 2023-11-28 15:53:31,610] Trial 15 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:31,793] Trial 15 failed with value None.
[W 2023-11-28 15:53:31,610] Trial 16 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:31,977] Trial 16 failed with value None.
[W 2023-11-28 15:53:31,976] Trial 17 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:32,159] Trial 17 failed with value None.
[W 2023-11-28 15:53:32,341] Trial 18 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:32,345] Trial 18 failed with value None.
[W 2023-11-28 15:53:32,342] Trial 19 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:32,529] Trial 19 failed with value None.
[W 2023-11-28 15:53:32,344] Trial 21 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:32,713] Trial 21 failed with value None.
[W 2023-11-28 15:53:32,528] Trial 23 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:32,899] Trial 23 failed with value None.
[W 2023-11-28 15:53:32,343] Trial 20 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:33,084] Trial 20 failed with value None.
[W 2023-11-28 15:53:32,712] Trial 25 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:33,269] Trial 25 failed with value None.
[W 2023-11-28 15:53:32,897] Trial 27 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:33,453] Trial 27 failed with value None.
[W 2023-11-28 15:53:33,080] Trial 28 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:33,081] Trial 29 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:33,636] Trial 29 failed with value None.
[W 2023-11-28 15:53:33,082] Trial 30 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:33,821] Trial 30 failed with value None.
[W 2023-11-28 15:53:33,083] Trial 32 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:34,006] Trial 32 failed with value None.
[W 2023-11-28 15:53:32,528] Trial 22 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:34,186] Trial 22 failed with value None.
[W 2023-11-28 15:53:33,269] Trial 35 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:34,371] Trial 35 failed with value None.
[W 2023-11-28 15:53:33,453] Trial 37 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:34,557] Trial 37 failed with value None.
[W 2023-11-28 15:53:32,529] Trial 24 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:34,741] Trial 24 failed with value None.
[W 2023-11-28 15:53:33,082] Trial 31 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:34,926] Trial 31 failed with value None.
[W 2023-11-28 15:53:33,821] Trial 39 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:35,111] Trial 39 failed with value None.
[W 2023-11-28 15:53:33,268] Trial 34 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:35,297] Trial 34 failed with value None.
[W 2023-11-28 15:53:33,269] Trial 36 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:35,483] Trial 36 failed with value None.
[W 2023-11-28 15:53:33,636] Trial 28 failed with value None.
[W 2023-11-28 15:53:33,084] Trial 33 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:35,847] Trial 33 failed with value None.
[W 2023-11-28 15:53:35,111] Trial 41 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:36,030] Trial 41 failed with value None.
[W 2023-11-28 15:53:35,111] Trial 42 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:36,212] Trial 42 failed with value None.
[W 2023-11-28 15:53:35,295] Trial 44 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:36,397] Trial 44 failed with value None.
[W 2023-11-28 15:53:35,296] Trial 46 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:36,578] Trial 46 failed with value None.
[W 2023-11-28 15:53:32,896] Trial 26 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:36,760] Trial 26 failed with value None.
[W 2023-11-28 15:53:34,005] Trial 40 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:36,945] Trial 40 failed with value None.
[W 2023-11-28 15:53:35,296] Trial 45 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:37,128] Trial 45 failed with value None.
[W 2023-11-28 15:53:33,820] Trial 38 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:37,309] Trial 38 failed with value None.
[W 2023-11-28 15:53:35,297] Trial 47 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:37,490] Trial 47 failed with value None.
[W 2023-11-28 15:53:35,294] Trial 43 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:37,673] Trial 43 failed with value None.
Traceback (most recent call last):
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/small_main.py", line 107, in <module>
    main()
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/small_main.py", line 69, in main
    automodel.fit(X=X_train_missing)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 61, in fit
    self.study.optimize(obj, n_trials=self.n_trials, n_jobs=self.n_jobs, show_progress_bar=self.show_progress, gc_after_trial=self.garbage_collect)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/study.py", line 451, in optimize
    _optimize(
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 103, in _optimize
    f.result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    raise func_err
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
srun: error: esplhpc-cp004: task 0: Exited with exit code 1
